### ISSUE TITLE
Mistake in collision

### ISSUE THREAD

**Issue by AndrobaL** [GardeningTool/Mercury#2]
CollisionUtil.java ligne 154
![image](https://user-images.githubusercontent.com/43884065/145972104-fab0ef84-2f90-4dc3-adb4-d3acdce30ea6.png)
change from.maxX >= to.minY with from.maxX >= to.minX

**Comment by GardeningTool** [comment]
Fixed, I appreciate it.

**Comment by AndrobaL** [comment]
No prob can I have your discord ?

**Comment by GardeningTool** [comment]
george.#2952
